// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crdxmhwzdzyeypvbfjpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZHhtaHd6ZHp5ZXlwdmJmanBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDg5MjksImV4cCI6MjA1OTgyNDkyOX0.6gdJEuWxXRs2SyuBB6TCnKqSLf9V7Bgc0sLfUB5-sTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);